### ISSUE TITLE
keyError for Windows with OR 2.5

### ISSUE THREAD

**Issue by nathanhilbert** [paulmakepeace/refine-client-py#6]
I just wanted to double check if this is happening to anyone else.  I'm getting a keyError on the columns after a new_project call with a project_url parameter.  I've tried all combinations I could think of including OR 2.5 (latest) and OR 2.6 with refine-client-py master, back to master https://github.com/PaulMakepeace/refine-client-py/commit/1a4f00b3cdc0fca321ec774a8667306fb6ad9c29 , and the pypi install in Windows 2008 and Ubuntu 12.04.  All give the same result of keyError keyColumnName with any dataset I throw at it.  The error is shown below.  The output from OR is shown below that.  When I open the OR client the browser, the project is created but there are no data in it.  If this is an error that can be replicated by other people, then I wonder if the create-import-job with using the importing-controller wouldn't be a better approach over create-project-from-upload as shown here (https://groups.google.com/forum/#!topic/openrefine-dev/oh5Cic1XVcI).  Any thoughts would be appreciated.

```
>>> refiner.new_project(project_url="https://raw.githubusercontent.com/PaulMakepeace/refine-client-py/master/tests/data/duplicates.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\pythonex\python27_64\lib\site-packages\google\ref
ine\refine.py", line 279, in new_project
    return RefineProject(self.server, project_id)
  File "C:\Users\Administrator\pythonex\python27_64\lib\site-packages\google\ref
ine\refine.py", line 356, in __init__
    self.get_models()
  File "C:\Users\Administrator\pythonex\python27_64\lib\site-packages\google\ref
ine\refine.py", line 407, in get_models
    self.key_column = column_model['keyColumnName']
KeyError: 'keyColumnName'
```

```
13:38:31.753 [                   refine] POST /command/core/create-project-from-
upload (508ms)
13:38:31.815 [                   refine] GET /command/core/get-models (62ms)
```

**Comment by paulmakepeace** [comment]
Hi Nathan,

The `new_project(project_url=...)` call is intended to be passed a Refine Server URL rather than an arbitrary URL to download. 

Take a look in https://github.com/PaulMakepeace/refine-client-py/blob/master/tests/test_refine.py#L61 to see how it's being used.

If you want to work with a dataset, [download it](http://stackoverflow.com/questions/22676/how-do-i-download-a-file-over-http-using-python) beforehand then point at it with the `project_file=` parameter.

`project_server_url=` probably would have been a better choice of parameter name...

**Comment by nathanhilbert** [comment]
Thanks @PaulMakepeace for your response.  You're correct that I thought project_url and project_file were interchangeable.  Sorry I didn't notice that in the tests.  I was trying to create the error I was getting in the simplest way.  I should have just started with the tests.  This is a Windows 2008, python 2.7 x64, and OpenRefine 2.5 latest.  See the output from latest master refine_client from the python setup.py test command:

```
(refinevir) C:\tmp\refine-client>python setup.py test
running test
running egg_info
writing requirements to refine_client.egg-info\requires.txt
writing refine_client.egg-info\PKG-INFO
writing top-level names to refine_client.egg-info\top_level.txt
writing dependency_links to refine_client.egg-info\dependency_links.txt
reading manifest file 'refine_client.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'refine_client.egg-info\SOURCES.txt'
running build_ext
test_from_camel (tests.test_facet.CamelTest) ... ok
test_to_camel (tests.test_facet.CamelTest) ... ok
test_add_facet (tests.test_facet.EngineTest) ... ok
test_init (tests.test_facet.EngineTest) ... ok
test_reset_remove (tests.test_facet.EngineTest) ... ok
test_serialize (tests.test_facet.EngineTest) ... ok
test_init (tests.test_facet.FacetTest) ... ok
test_selections (tests.test_facet.FacetTest) ... ok
test_facet_response (tests.test_facet.FacetsResponseTest) ... ok
test_sorting (tests.test_facet.SortingTest) ... ok
test_init (tests.test_history.HistoryTest) ... ok
test_get_version (tests.test_refine.RefineServerTest) ... ok
test_init (tests.test_refine.RefineServerTest) ... ok
test_list_projects (tests.test_refine.RefineServerTest) ... ok
test_version (tests.test_refine.RefineServerTest) ... ok
test_delete_project (tests.test_refine.RefineTest) ... ERROR
test_get_models (tests.test_refine.RefineTest) ... ERROR
test_new_project (tests.test_refine.RefineTest) ... ERROR
test_open_export (tests.test_refine.RefineTest) ... ERROR
test_open_export_csv (tests.test_refine.RefineTest) ... ERROR
test_wait_until_idle (tests.test_refine.RefineTest) ... ERROR
test_server_init (tests.test_refine_small.RefineProjectTest) ... ok
test_rows_response (tests.test_refine_small.RefineRowsTest) ... ok
test_duplicate_detection (tests.test_tutorial.TutorialTestDuplicateDetection) ..
. ERROR
test_editing (tests.test_tutorial.TutorialTestEditing) ... ERROR
test_facet (tests.test_tutorial.TutorialTestFacets) ... ERROR
test_get_rows (tests.test_tutorial.TutorialTestFacets) ... ERROR
test_transpose_columns_into_rows (tests.test_tutorial.TutorialTestTransposeColum
nsIntoRows) ... ERROR
test_transpose_fixed_number_of_rows_into_columns (tests.test_tutorial.TutorialTe
stTransposeFixedNumberOfRowsIntoColumns) ... ERROR
test_transpose_variable_number_of_rows_into_columns (tests.test_tutorial.Tutoria
lTestTransposeVariableNumberOfRowsIntoColumns) ... ERROR
test_web_scraping (tests.test_tutorial.TutorialTestWebScraping) ... ERROR

======================================================================
ERROR: test_delete_project (tests.test_refine.RefineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\tmp\refine-client\tests\refinetest.py", line 39, in setUp
    project_file=self.project_path(), project_format=self.project_format, **self
.project_options)
  File "c:\tmp\refine-client\google\refine\refine.py", line 279, in new_project
    return RefineProject(self.server, project_id)
  File "c:\tmp\refine-client\google\refine\refine.py", line 356, in __init__
    self.get_models()
  File "c:\tmp\refine-client\google\refine\refine.py", line 402, in get_models
    self.key_column = column_model['keyColumnName']
KeyError: 'keyColumnName'
```

And from openrefine:

```
10:43:48.626 [                   refine] GET /command/core/get-version (35129ms)

10:43:48.643 [                   refine] GET /command/core/get-all-project-metad
ata (17ms)
10:43:48.660 [                   refine] GET /command/core/get-version (17ms)
10:43:48.677 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:49.460 [                   refine] GET /command/core/get-models (783ms)
10:43:49.460 [                   refine] POST /command/core/create-project-from-
upload (0ms)
10:43:49.613 [                   refine] GET /command/core/get-models (153ms)
10:43:49.630 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:49.732 [                   refine] GET /command/core/get-models (102ms)
10:43:49.749 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:49.834 [                   refine] GET /command/core/get-models (85ms)
10:43:49.851 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:49.919 [                   refine] GET /command/core/get-models (68ms)
10:43:49.936 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:49.987 [                   refine] GET /command/core/get-models (51ms)
10:43:50.004 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:50.055 [                   refine] GET /command/core/get-models (51ms)
10:43:50.072 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:50.174 [                   refine] GET /command/core/get-models (102ms)
10:43:50.174 [                   refine] POST /command/core/create-project-from-
upload (0ms)
10:43:50.294 [                   refine] GET /command/core/get-models (120ms)
10:43:50.311 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:50.379 [                   refine] GET /command/core/get-models (68ms)
10:43:50.379 [                   refine] POST /command/core/create-project-from-
upload (0ms)
10:43:50.430 [                   refine] GET /command/core/get-models (51ms)
10:43:50.430 [                   refine] POST /command/core/create-project-from-
upload (0ms)
10:43:50.464 [                   refine] GET /command/core/get-models (34ms)
10:43:50.481 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:50.515 [                   refine] GET /command/core/get-models (34ms)
10:43:50.532 [                   refine] POST /command/core/create-project-from-
upload (17ms)
10:43:50.566 [                   refine] GET /command/core/get-models (34ms)
10:48:13.884 [          project_manager] Saving some modified projects ... (2633
18ms)
```

Thanks again.

**Comment by paulmakepeace** [comment]
So are you saying the tests are failing out of the box?

I've tested refine-client-py HEAD with `Python 2.7.5 (default, Mar  9 2014, 22:15:05)` and Google/OpenRefine r2407 ("2.5") on Mac OS X and all are passing.

If you're still having trouble I'd suggest asking on the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/openrefine) since I don't have access to Windows.

**Comment by nathanhilbert** [comment]
Thanks.  Leaving open so others are aware that only OR2.1 works in Windows not 2.5 or 2.6 for now.  Also, retitling.
